# Generated by Django 5.0.4 on 2024-05-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haber',
            old_name='title',
            new_name='baslik',
        ),
        migrations.RenameField(
            model_name='haber',
            old_name='content',
            new_name='icerik',
        ),
        migrations.RenameField(
            model_name='haber',
            old_name='date_posted',
            new_name='tarih',
        ),
    ]
