# Generated by Django 5.0.4 on 2024-05-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_haber_baslik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='haber_resimleri/'),
        ),
    ]
